### ISSUE TITLE
请问这个支持按钮上下布局吗

### ISSUE THREAD

**Issue by addappcn** [beefe/react-native-popupwindow#2]

**Comment by shexiaoheng** [comment]
这个布局是在[Android的布局文件](https://github.com/beefe/react-native-popupwindow/blob/master/src/main/res/layout/popup_window.xml)定义的，目前不支持上下布局。

**Comment by addappcn** [comment]
谢谢，那我只能基于你的代码改布局了

**Comment by shexiaoheng** [comment]
@addappcn 你的需求是什么样子的？给我个截个图，我找个时间加上支持。

**Comment by shexiaoheng** [comment]
@addappcn 已添加上下布局，不知道是不是你需要的，可以看下运行效果图。

**Comment by xwenliang** [comment]
@addappcn 可以试试这个 https://github.com/beefe/react-native-actionsheet
